#
# LibreSignage stage 1 makefile.
#

include makefile.common

# Define required dependency versions.
NPM_REQ_VER := 6.4.0
COMPOSER_REQ_VER := 1.8.0
MAKE_REQ_VER := 4.0
PANDOC_REQ_VER := 2.0
DOXYGEN_REQ_VER := 1.8.0
RSVG_REQ_VER := 2.40.0

.ONESHELL:

all: initchk

# Perform some initialization checks.
initchk:
	@:
	set +e
	tmp=0
	./build/scripts/check_shell.sh
	tmp=$$(expr $$tmp + $$?)
	./build/scripts/dep_checks/npm_version.sh $(NPM_REQ_VER)
	tmp=$$(expr $$tmp + $$?)
	./build/scripts/dep_checks/composer_version.sh $(COMPOSER_REQ_VER)
	tmp=$$(expr $$tmp + $$?)
	./build/scripts/dep_checks/make_version.sh $(MAKE_REQ_VER)
	tmp=$$(expr $$tmp + $$?)
	./build/scripts/dep_checks/pandoc_version.sh $(PANDOC_REQ_VER)
	tmp=$$(expr $$tmp + $$?)
	./build/scripts/dep_checks/rsvg_version.sh $(RSVG_REQ_VER)
	tmp=$$(expr $$tmp + $$?)
	./build/scripts/dep_checks/doxygen_version.sh $(DOXYGEN_REQ_VER)
	tmp=$$(expr $$tmp + $$?)

	$(call initchk_warn,$$tmp)

