<?php

/*
*  SlideLock object implementation needed in the Slide class.
*/

require_once($_SERVER['DOCUMENT_ROOT'].'/common/php/config.php');

class SlideLock {
	private $user = NULL;
	private $expire = NULL;

	public function __construct($user) {
		if (!empty($user)) {
			$this->user = $user;
			$this->expire = time() + SLIDE_LOCK_MAX_AGE;
		}
	}

	public function load(array $data) {
		/*
		*  Load lock data from an array originally
		*  generated by SlideLock::export().
		*/
		if (
			!array_key_exists('user', $data)
			|| !array_key_exists('expire', $data)
		) {
			throw new ArgException('Invalid SlideLock data.');
		}
		$this->user = $data['user'];
		$this->expire = $data['expire'];
	}

	public function export() {
		/*
		*  Export the SlideLock data for JSON encoding and
		*  storing on the filesystem.
		*/
		return [
			'user' => $this->user,
			'expire' => $this->expire
		];
	}

	public function get_user() {
		return $this->user;
	}
	
	public function get_expire() {
		return $this->expire;
	}

	public function is_expired() {
		return empty($this->user) || time() > $this->expire;
	}
}
