<?php

/*
*  SlideLock object implementation needed in the Slide class.
*/

require_once($_SERVER['DOCUMENT_ROOT'].'/common/php/config.php');

class SlideLock {
	private $EXPORTED = [
		'session_id',
		'expire'
	];
	private $session_id = NULL;
	private $expire = NULL;

	public function __construct($session) {
		if (!empty($session)) {
			$this->session_id = $session->get_id();
			$this->expire = time() + SLIDE_LOCK_MAX_AGE;
		}
	}

	public function load(array $data) {
		/*
		*  Load lock data from an array originally
		*  generated by SlideLock::export().
		*/
		foreach ($this->EXPORTED as $k) {
			if (!array_key_exists($k, $data)) {
				throw new ArgException('Invalid SlideLock data.');
			}
			$this->{$k} = $data[$k];
		}
	}

	public function export() {
		/*
		*  Export the SlideLock data as an array.
		*/
		$ret = [];
		foreach ($this->EXPORTED as $k) { $ret[$k] = $this->{$k}; }
		return $ret;
	}

	public function is_expired() {
		return empty($this->session_id) || time() > $this->expire;
	}

	public function is_owned_by(Session $session) {
		return $this->session_id === $session->get_id();
	}

	public function get_session_id() { return $this->session_id; }
	public function get_expire() { return $this->expire; }
}
