<!-- Favicons for the LibreSignage web interface. -->
<link
	rel="icon"
	type="image/png"
	href="/assets/images/logo/libresignage_16x16.png"
	sizes="16x16">
<link
	rel="icon"
	type="image/png"
	href="/assets/images/logo/libresignage_32x32.png"
	sizes="32x32">
<link
	rel="icon"
	type="image/png"
	href="/assets/images/logo/libresignage_96x96.png"
	sizes="96x96">
<link
	rel="icon"
	type="image/svg+xml"
	href="/assets/images/logo/libresignage.svg">
